# Generated by Django 4.0 on 2021-12-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='href',
            field=models.CharField(default='#', max_length=20, verbose_name='ссылка'),
        ),
    ]
